### ISSUE TITLE
For frame [livox]: Fixed Frame [camera_init] does not exist!!!

### ISSUE THREAD

**Issue by ccq0905** [GDUT-Kyle/LINS-LIVOX#2]
Looking forward to your reply!
![Screenshot from 2022-04-21 21-48-32](https://user-images.githubusercontent.com/104149220/164473094-1e1f35e1-d024-4b5b-b4c4-f2a54d5dbedc.png)

**Comment by GDUT-Kyle** [comment]
Since we set use_sim_time in the launch file:
```
<param name="/use_sim_time" value="true" />
```
Therefore, you need to add `--clock` when playing rosbag, as:
```
rosbag play 2022-01-14-19-56-48.bag --clock
```

**Comment by GDUT-Kyle** [comment]
你好，我是Zhao，我已接收到你的邮件！
