### ISSUE TITLE
cloud_msgs

### ISSUE THREAD

**Issue by Minsu-Kim1822** [GDUT-Kyle/LINS-LIVOX#4]
Hi I wanna use this but cloud_msgs cannot found.
I already compiled with livox_ros_driver.

what is the problem?

**Comment by GDUT-Kyle** [comment]
Hi, excuse my laziness, `cloud_msgs` can be found in [LeGO-LOAM](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM), but I actually recommend faster_lio_sam (but only if you have a nine axis IMU).

**Comment by Minsu-Kim1822** [comment]
It's ok. it works for me. thanks.
However,  is there any articles or paper about this algorithm?

**Comment by GDUT-Kyle** [comment]
You can reference [LINS---LiDAR-inertial-SLAM](https://github.com/ChaoqinRobotics/LINS---LiDAR-inertial-SLAM)

**Comment by Minsu-Kim1822** [comment]
Thanks for your help :)
